//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS.OrangeAdmin.DataProvider.OrangeAdminService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryParameters", Namespace="http://schemas.datacontract.org/2004/07/DS.OrangeAdmin.Server.Queries")]
    [System.SerializableAttribute()]
    public partial class QueryParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] FiltrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TakeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Filtros {
            get {
                return this.FiltrosField;
            }
            set {
                if ((object.ReferenceEquals(this.FiltrosField, value) != true)) {
                    this.FiltrosField = value;
                    this.RaisePropertyChanged("Filtros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Take {
            get {
                return this.TakeField;
            }
            set {
                if ((this.TakeField.Equals(value) != true)) {
                    this.TakeField = value;
                    this.RaisePropertyChanged("Take");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrangeAdminService.IOrangeAdmin")]
    public interface IOrangeAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrangeAdmin/GetClients", ReplyAction="http://tempuri.org/IOrangeAdmin/GetClientsResponse")]
        DS.OrangeAdmin.Core.DTO.ClientDTO[] GetClients(DS.OrangeAdmin.DataProvider.OrangeAdminService.QueryParameters queryParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrangeAdmin/GetClients", ReplyAction="http://tempuri.org/IOrangeAdmin/GetClientsResponse")]
        System.Threading.Tasks.Task<DS.OrangeAdmin.Core.DTO.ClientDTO[]> GetClientsAsync(DS.OrangeAdmin.DataProvider.OrangeAdminService.QueryParameters queryParameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrangeAdminChannel : DS.OrangeAdmin.DataProvider.OrangeAdminService.IOrangeAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrangeAdminClient : System.ServiceModel.ClientBase<DS.OrangeAdmin.DataProvider.OrangeAdminService.IOrangeAdmin>, DS.OrangeAdmin.DataProvider.OrangeAdminService.IOrangeAdmin {
        
        public OrangeAdminClient() {
        }
        
        public OrangeAdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrangeAdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrangeAdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrangeAdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DS.OrangeAdmin.Core.DTO.ClientDTO[] GetClients(DS.OrangeAdmin.DataProvider.OrangeAdminService.QueryParameters queryParameters) {
            return base.Channel.GetClients(queryParameters);
        }
        
        public System.Threading.Tasks.Task<DS.OrangeAdmin.Core.DTO.ClientDTO[]> GetClientsAsync(DS.OrangeAdmin.DataProvider.OrangeAdminService.QueryParameters queryParameters) {
            return base.Channel.GetClientsAsync(queryParameters);
        }
    }
}
