//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS.OrangeAdmin.DataProvider.OrangeAdminService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrangeAdminService.IOrangeAdmin")]
    public interface IOrangeAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrangeAdmin/GetClient", ReplyAction="http://tempuri.org/IOrangeAdmin/GetClientResponse")]
        DS.OrangeAdmin.Core.Operations.OperationResult<DS.OrangeAdmin.Core.DTO.ClientDTO> GetClient(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrangeAdmin/GetClient", ReplyAction="http://tempuri.org/IOrangeAdmin/GetClientResponse")]
        System.Threading.Tasks.Task<DS.OrangeAdmin.Core.Operations.OperationResult<DS.OrangeAdmin.Core.DTO.ClientDTO>> GetClientAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrangeAdmin/GetClients", ReplyAction="http://tempuri.org/IOrangeAdmin/GetClientsResponse")]
        DS.OrangeAdmin.Core.Operations.OperationResult<System.Collections.Generic.List<DS.OrangeAdmin.Core.DTO.ClientDTO>> GetClients(DS.OrangeAdmin.Server.Queries.QueryParameters parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrangeAdmin/GetClients", ReplyAction="http://tempuri.org/IOrangeAdmin/GetClientsResponse")]
        System.Threading.Tasks.Task<DS.OrangeAdmin.Core.Operations.OperationResult<System.Collections.Generic.List<DS.OrangeAdmin.Core.DTO.ClientDTO>>> GetClientsAsync(DS.OrangeAdmin.Server.Queries.QueryParameters parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrangeAdmin/SaveClient", ReplyAction="http://tempuri.org/IOrangeAdmin/SaveClientResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DS.OrangeAdmin.Core.Operations.OperationResult<System.Collections.Generic.List<DS.OrangeAdmin.Core.DTO.ClientDTO>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DS.OrangeAdmin.Core.Operations.OperationResult<DS.OrangeAdmin.Core.DTO.ClientDTO>))]
        DS.OrangeAdmin.Core.Operations.OperationResult SaveClient(DS.OrangeAdmin.Core.DTO.ClientDTO client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrangeAdmin/SaveClient", ReplyAction="http://tempuri.org/IOrangeAdmin/SaveClientResponse")]
        System.Threading.Tasks.Task<DS.OrangeAdmin.Core.Operations.OperationResult> SaveClientAsync(DS.OrangeAdmin.Core.DTO.ClientDTO client);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrangeAdminChannel : DS.OrangeAdmin.DataProvider.OrangeAdminService.IOrangeAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrangeAdminClient : System.ServiceModel.ClientBase<DS.OrangeAdmin.DataProvider.OrangeAdminService.IOrangeAdmin>, DS.OrangeAdmin.DataProvider.OrangeAdminService.IOrangeAdmin {
        
        public OrangeAdminClient() {
        }
        
        public OrangeAdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrangeAdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrangeAdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrangeAdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DS.OrangeAdmin.Core.Operations.OperationResult<DS.OrangeAdmin.Core.DTO.ClientDTO> GetClient(System.Guid id) {
            return base.Channel.GetClient(id);
        }
        
        public System.Threading.Tasks.Task<DS.OrangeAdmin.Core.Operations.OperationResult<DS.OrangeAdmin.Core.DTO.ClientDTO>> GetClientAsync(System.Guid id) {
            return base.Channel.GetClientAsync(id);
        }
        
        public DS.OrangeAdmin.Core.Operations.OperationResult<System.Collections.Generic.List<DS.OrangeAdmin.Core.DTO.ClientDTO>> GetClients(DS.OrangeAdmin.Server.Queries.QueryParameters parameters) {
            return base.Channel.GetClients(parameters);
        }
        
        public System.Threading.Tasks.Task<DS.OrangeAdmin.Core.Operations.OperationResult<System.Collections.Generic.List<DS.OrangeAdmin.Core.DTO.ClientDTO>>> GetClientsAsync(DS.OrangeAdmin.Server.Queries.QueryParameters parameters) {
            return base.Channel.GetClientsAsync(parameters);
        }
        
        public DS.OrangeAdmin.Core.Operations.OperationResult SaveClient(DS.OrangeAdmin.Core.DTO.ClientDTO client) {
            return base.Channel.SaveClient(client);
        }
        
        public System.Threading.Tasks.Task<DS.OrangeAdmin.Core.Operations.OperationResult> SaveClientAsync(DS.OrangeAdmin.Core.DTO.ClientDTO client) {
            return base.Channel.SaveClientAsync(client);
        }
    }
}
